/**
 * Auto-generated by Forge for board: basic_board
 * MCU: stm32f4 @ 84 MHz
 * DO NOT EDIT — regenerate from board.toml
 */

#ifndef FORGE_INIT_H
#define FORGE_INIT_H

#include <stdint.h>

/* GPIO */
void gpio_init_all(void);

/* UART */
void uart_console_init(void);
void uart_console_send(const uint8_t *data, uint16_t len);

/* Master init */
void board_init(void);

#endif /* FORGE_INIT_H */
