/**
 * Auto-generated by Forge for board: sensor_hub
 * MCU: stm32f4 @ 168 MHz
 * DO NOT EDIT — regenerate from board.toml
 */

#ifndef FORGE_INIT_H
#define FORGE_INIT_H

#include <stdint.h>

/* GPIO */
void gpio_init_sensor_power(void);
void gpio_init_cs_flash(void);

/* I2C */
void i2c_sensor_bus_init(void);
void i2c_sensor_bus_write(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);
void i2c_sensor_bus_read(uint8_t addr, uint8_t reg, uint8_t *data, uint16_t len);
void i2c_i2c_mux_init(void);
void i2c_imu_init(void);
void i2c_barometer_init(void);

/* SPI */
void spi_storage_bus_init(void);
void spi_flash_init(void);
void spi_flash_select(void);
void spi_flash_deselect(void);
void spi_storage_bus_transfer(uint8_t *tx, uint8_t *rx, uint16_t len);

/* Master init */
void board_init(void);

#endif /* FORGE_INIT_H */
