//! The Zephyr backend: emit a devicetree overlay plus a `prj.conf` from the IR.
//!
//! This targets the single most-complained-about part of Zephyr — hand-writing
//! devicetree nodes. From the same board description that drives the C backend,
//! it produces a structurally valid `.overlay` and a matching Kconfig fragment.
//!
//! Honesty note: an overlay layers onto a specific SoC's base devicetree, so the
//! controller labels (`&i2c0`, `&spi0`, `&gpio0`, …) and device `compatible`
//! strings must be matched to your board. The generated file marks those spots
//! with comments rather than guessing silently.

use super::{Backend, GeneratedFile, InitPlan};
use crate::model::{Board, GpioMode};

/// Emits `<board>.overlay` and `prj.conf` for a Zephyr application.
pub struct ZephyrBackend;

impl Backend for ZephyrBackend {
    fn id(&self) -> &'static str {
        "zephyr"
    }

    fn description(&self) -> &'static str {
        "Zephyr RTOS devicetree overlay + prj.conf"
    }

    fn render(&self, board: &Board, _plan: &InitPlan) -> Vec<GeneratedFile> {
        vec![
            GeneratedFile::new(
                format!("{}.overlay", sanitize_filename(&board.name)),
                render_overlay(board),
            ),
            GeneratedFile::new("prj.conf", render_prj_conf(board)),
        ]
    }
}

/// Render the devicetree overlay.
fn render_overlay(board: &Board) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/*\n * Auto-generated by Forge for board: {}\n \
         * MCU: {} @ {} MHz\n \
         * Devicetree overlay. Adjust controller labels (&i2c0, &spi0, &gpio0, ...)\n \
         * and device `compatible` strings to match your SoC.\n */\n\n",
        board.name, board.mcu, board.clock_mhz
    ));
    s.push_str("#include <zephyr/dt-bindings/gpio/gpio.h>\n\n");

    // Root node: aliases + gpio groupings.
    let outputs: Vec<_> = board.gpios.iter().filter(|g| g.is_output()).collect();
    let inputs: Vec<_> = board.gpios.iter().filter(|g| !g.is_output()).collect();

    if !board.gpios.is_empty() {
        s.push_str("/ {\n");
        s.push_str("    aliases {\n");
        for g in &board.gpios {
            s.push_str(&format!(
                "        {} = &{};\n",
                alias_name(&g.label),
                g.label
            ));
        }
        s.push_str("    };\n");

        if !outputs.is_empty() {
            s.push_str("\n    forge_outputs {\n");
            s.push_str("        compatible = \"gpio-leds\";\n");
            for g in &outputs {
                s.push_str(&format!(
                    "        {label}: out_{label} {{\n            \
                     gpios = <&gpio0 {pin} GPIO_ACTIVE_HIGH>;\n            \
                     label = \"{label}\";\n        }};\n",
                    label = g.label,
                    pin = g.pin
                ));
            }
            s.push_str("    };\n");
        }

        if !inputs.is_empty() {
            s.push_str("\n    forge_inputs {\n");
            s.push_str("        compatible = \"gpio-keys\";\n");
            for g in &inputs {
                let intr = match g.interrupt {
                    Some(edge) => format!("            /* interrupt: {} */\n", edge.describe()),
                    None => String::new(),
                };
                s.push_str(&format!(
                    "        {label}: in_{label} {{\n            \
                     gpios = <&gpio0 {pin} {flags}>;\n            \
                     label = \"{label}\";\n{intr}        }};\n",
                    label = g.label,
                    pin = g.pin,
                    flags = gpio_flags(g.mode),
                    intr = intr,
                ));
            }
            s.push_str("    };\n");
        }
        s.push_str("};\n");
    }

    // I2C buses.
    for bus in &board.i2c_buses {
        s.push_str(&format!("\n&i2c{} {{\n", bus.bus));
        s.push_str("    status = \"okay\";\n");
        s.push_str(&format!(
            "    clock-frequency = <{}>;\n",
            bus.speed_khz * 1000
        ));
        for d in &bus.devices {
            s.push_str(&format!(
                "    {label}: {label}@{addr:x} {{\n        \
                 /* set compatible = \"vendor,part\"; */\n        \
                 reg = <0x{addr:x}>;\n    }};\n",
                label = d.label,
                addr = d.address
            ));
        }
        s.push_str("};\n");
    }

    // SPI buses.
    for bus in &board.spi_buses {
        s.push_str(&format!("\n&spi{} {{\n", bus.bus));
        s.push_str("    status = \"okay\";\n");
        if !bus.devices.is_empty() {
            let cs = bus
                .devices
                .iter()
                .map(|d| format!("<&gpio0 {} GPIO_ACTIVE_LOW>", d.cs_pin))
                .collect::<Vec<_>>()
                .join(", ");
            s.push_str(&format!("    cs-gpios = {cs};\n"));
        }
        for (i, d) in bus.devices.iter().enumerate() {
            s.push_str(&format!(
                "    {label}: {label}@{i} {{\n        \
                 /* set compatible = \"vendor,part\"; */\n        \
                 reg = <{i}>;\n        \
                 spi-max-frequency = <{hz}>;\n    }};\n",
                label = d.label,
                i = i,
                hz = d.speed_mhz * 1_000_000,
            ));
        }
        s.push_str("};\n");
    }

    // UARTs.
    for u in &board.uarts {
        s.push_str(&format!("\n&uart{} {{\n", u.index));
        s.push_str("    status = \"okay\";\n");
        s.push_str(&format!("    current-speed = <{}>;\n", u.baud));
        s.push_str("    /* TX/RX pins are set via the SoC pinctrl, not here. */\n");
        s.push_str("};\n");
    }

    s
}

/// Render the `prj.conf` Kconfig fragment, enabling only the subsystems used.
fn render_prj_conf(board: &Board) -> String {
    let mut s = format!("# Auto-generated by Forge for board: {}\n", board.name);
    if !board.gpios.is_empty() {
        s.push_str("CONFIG_GPIO=y\n");
    }
    if !board.i2c_buses.is_empty() {
        s.push_str("CONFIG_I2C=y\n");
    }
    if !board.spi_buses.is_empty() {
        s.push_str("CONFIG_SPI=y\n");
    }
    if !board.uarts.is_empty() {
        s.push_str("CONFIG_SERIAL=y\n");
        s.push_str("CONFIG_UART_INTERRUPT_DRIVEN=y\n");
    }
    s
}

/// Devicetree GPIO flag expression for a pin mode.
fn gpio_flags(mode: GpioMode) -> &'static str {
    match mode {
        GpioMode::Output => "GPIO_ACTIVE_HIGH",
        GpioMode::Input => "GPIO_ACTIVE_HIGH",
        GpioMode::InputPullup => "(GPIO_PULL_UP | GPIO_ACTIVE_LOW)",
        GpioMode::InputPulldown => "(GPIO_PULL_DOWN | GPIO_ACTIVE_HIGH)",
    }
}

/// Alias property names conventionally use hyphens, not underscores.
fn alias_name(label: &str) -> String {
    label.replace('_', "-")
}

/// Make a board name safe for a file stem.
fn sanitize_filename(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if cleaned.is_empty() {
        "board".to_string()
    } else {
        cleaned
    }
}
