//! The auto-generated file banner shared by generated headers.

use crate::model::Board;

/// Render the doc-comment banner placed at the top of `init.h`.
///
/// ```c
/// /**
///  * Auto-generated by Forge for board: jupiter_v2
///  * MCU: esp32c6 @ 160 MHz
///  * DO NOT EDIT — regenerate from board.toml
///  */
/// ```
pub fn file_banner(board: &Board) -> String {
    let mut s = String::new();
    s.push_str("/**\n");
    s.push_str(&format!(
        " * Auto-generated by Forge for board: {}\n",
        board.name
    ));
    s.push_str(&format!(
        " * MCU: {} @ {} MHz\n",
        board.mcu, board.clock_mhz
    ));
    s.push_str(" * DO NOT EDIT — regenerate from board.toml\n");
    s.push_str(" */\n");
    s
}
